In [136]:
import pandas as pd

### Read in Aircraft List

In [137]:
df=pd.read_json('http://carterhumphreys.com/ads-b/aircraft.json')
df['now'][0]

1585777141

### Extract ADS-B Data from Aircraft List

In [138]:
df=pd.DataFrame(df['aircraft'].tolist())
df

,hex,alt_baro,alt_geom,gs,track,baro_rate,nav_qnh,nav_altitude_mcp,nav_heading,lat,...,mag_heading,geom_rate,squawk,category,emergency,nav_modes,tas,roll,track_rate,nav_altitude_fms
0,a54aae,36000.0,35525.0,444.6,334.7,0.0,1013.6,36000.0,345.9,41.242350,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ad2062,26925.0,26300.0,419.3,294.7,1792.0,NaN,43008.0,NaN,41.563156,...,313.8,1152.0,1144,A2,NaN,NaN,NaN,NaN,NaN,NaN
2,aa9e6d,40975.0,40700.0,462.3,85.7,0.0,1013.6,40992.0,94.9,42.599674,...,NaN,NaN,6205,NaN,none,NaN,NaN,NaN,NaN,NaN
3,a491f1,38000.0,37650.0,444.8,278.4,64.0,1013.6,38016.0,291.1,40.840897,...,NaN,NaN,1535,A3,none,NaN,NaN,NaN,NaN,NaN
4,a55f31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,adf128,38000.0,37600.0,440.7,231.7,64.0,NaN,NaN,NaN,40.877975,...,NaN,NaN,NaN,A3,NaN,NaN,NaN,NaN,NaN,NaN
6,a8795a,24700.0,24775.0,458.1,105.7,-1664.0,1013.6,13024.0,NaN,41.324468,...,NaN,NaN,4142,A3,none,"[autopilot, vnav, tcas]",NaN,NaN,NaN,NaN
7,a64d9f,17975.0,17525.0,411.3,16.7,-1984.0,1012.0,11008.0,NaN,42.058318,...,27.2,-1984.0,3642,A2,none,NaN,420.0,-0.2,NaN,NaN
8,a2c635,40000.0,39600.0,408.4,259.8,0.0,1013.6,40000.0,277.0,42.468933,...,273.0,32.0,3531,A3,none,NaN,436.0,0.0,-0.03,40000.0
9,a894aa,24875.0,24475.0,478.5,95.9,-3008.0,1017.6,16992.0,103.4,42.197555,...,106.5,-3360.0,6742,A5,none,NaN,462.0,0.0,0.03,NaN
10,abd50f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A3,NaN,NaN,NaN,NaN,NaN,NaN
11,a144e5,35000.0,34425.0,484.3,77.6,64.0,1012.8,35008.0,89.3,42.366354,...,88.8,0.0,1507,A5,none,NaN,468.0,0.2,0.03,NaN
12,a83dc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A2,NaN,NaN,NaN,NaN,NaN,NaN
13,a08bdd,32600.0,32625.0,476.3,70.5,-1792.0,1008.0,28992.0,75.9,42.122746,...,NaN,NaN,NaN,A5,NaN,NaN,NaN,NaN,NaN,NaN
14,a8e29c,38000.0,37550.0,446.8,292.8,0.0,1013.6,38016.0,305.2,42.465317,...,303.9,32.0,1602,A4,none,NaN,470.0,-0.9,-0.03,NaN
15,a05cbe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A1,NaN,NaN,NaN,NaN,NaN,NaN
16,ab20df,38000.0,37575.0,432.5,290.2,0.0,1013.6,38016.0,302.3,42.043979,...,NaN,NaN,3056,A3,none,NaN,460.0,0.7,0.03,NaN
17,aa030b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A3,NaN,NaN,NaN,NaN,NaN,NaN
18,a95535,40000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A3,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
lat = df['lat'].values
lon = df['lon'].values
alt = df['alt_baro'].values